channels:
- defaults
dependencies:
- python=3.6.8
- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/14600832
  - azureml-defaults==0.1.0.14600832
  - azureml-pipeline-wrapper==0.1.0.14600832
name: project_environment
